use crate::models::{
    Config, DayTimetable, ParsedAbsence, ParsedLesson, TimeUnit, TimetableSearchItem,
    TimetableSearchTargetType, TimetableTarget, WeekTimetable, add_days,
    compare_absence_newest_first, format_date, get_monday, get_weekday_name, today_local,
};
use chrono::NaiveDate;

pub const DEMO_CLASS_ID: i64 = 4101;
pub const DEMO_ROOM_ID: i64 = 5207;
pub const DEMO_TEACHER_ID: i64 = 6302;

pub fn demo_config() -> Config {
    Config {
        school: "demo-campus".to_owned(),
        username: "portfolio".to_owned(),
        password: "demo".to_owned(),
        server: "demo.local".to_owned(),
    }
}

pub fn demo_search_index() -> Vec<TimetableSearchItem> {
    vec![
        TimetableSearchItem {
            r#type: TimetableSearchTargetType::Class,
            id: DEMO_CLASS_ID,
            name: "5AHIF".to_owned(),
            long_name: "5AHIF Software Engineering".to_owned(),
            search_text: "5AHIF software engineering senior class".to_owned(),
        },
        TimetableSearchItem {
            r#type: TimetableSearchTargetType::Room,
            id: DEMO_ROOM_ID,
            name: "LAB-7".to_owned(),
            long_name: "Interaction Lab 7".to_owned(),
            search_text: "LAB-7 interaction lab room makerspace".to_owned(),
        },
        TimetableSearchItem {
            r#type: TimetableSearchTargetType::Teacher,
            id: DEMO_TEACHER_ID,
            name: "MILL".to_owned(),
            long_name: "Mila Iller".to_owned(),
            search_text: "MILL mila iller teacher design systems".to_owned(),
        },
        TimetableSearchItem {
            r#type: TimetableSearchTargetType::Room,
            id: 5208,
            name: "AUD-2".to_owned(),
            long_name: "Auditorium 2".to_owned(),
            search_text: "AUD-2 auditorium stage room".to_owned(),
        },
        TimetableSearchItem {
            r#type: TimetableSearchTargetType::Teacher,
            id: 6308,
            name: "NOVA".to_owned(),
            long_name: "Noa Varga".to_owned(),
            search_text: "NOVA noa varga teacher innovation".to_owned(),
        },
    ]
}

pub fn demo_week_timetable(week_date: NaiveDate, target: &TimetableTarget) -> WeekTimetable {
    let monday = get_monday(week_date);
    let timegrid = demo_timegrid();
    let lessons_by_day = match target {
        TimetableTarget::Own => own_week_lessons(),
        TimetableTarget::Class { id, .. } if *id == DEMO_CLASS_ID => class_week_lessons(),
        TimetableTarget::Room { id, .. } if *id == DEMO_ROOM_ID => room_week_lessons(),
        TimetableTarget::Teacher { id, .. } if *id == DEMO_TEACHER_ID => teacher_week_lessons(),
        _ => own_week_lessons(),
    };

    let days = lessons_by_day
        .into_iter()
        .enumerate()
        .map(|(offset, lessons)| {
            let date = add_days(monday, offset as i64);
            DayTimetable {
                date,
                day_name: get_weekday_name(date),
                lessons,
            }
        })
        .collect();

    WeekTimetable { days, timegrid }
}

pub fn demo_absences() -> Vec<ParsedAbsence> {
    let today = today_local();
    let mut items = vec![
        absence(
            9101,
            add_days(today, -3),
            add_days(today, -3),
            "08:00",
            "09:40",
            false,
            "Unexcused",
            "Late train from Linz",
            "Arrival delay affected first double period.",
        ),
        absence(
            9102,
            add_days(today, -8),
            add_days(today, -8),
            "10:45",
            "12:35",
            true,
            "Excused",
            "Dentist",
            "Follow-up appointment after braces adjustment.",
        ),
        absence(
            9103,
            add_days(today, -14),
            add_days(today, -14),
            "11:45",
            "13:25",
            true,
            "Excused",
            "Hackathon travel",
            "Regional finals in Vienna.",
        ),
        absence(
            9104,
            add_days(today, -19),
            add_days(today, -19),
            "08:00",
            "08:50",
            false,
            "Pending",
            "Overslept",
            "Alarm battery died overnight.",
        ),
        absence(
            9105,
            add_days(today, -27),
            add_days(today, -27),
            "08:50",
            "10:45",
            true,
            "Excused",
            "Medical check",
            "Cardiology screening.",
        ),
        absence(
            9106,
            add_days(today, -34),
            add_days(today, -34),
            "13:40",
            "15:20",
            true,
            "Excused",
            "Competition",
            "Robotics showcase setup.",
        ),
        absence(
            9107,
            add_days(today, -41),
            add_days(today, -41),
            "09:55",
            "11:35",
            false,
            "Unexcused",
            "Missed connection",
            "Bus replacement service ran late.",
        ),
        absence(
            9108,
            add_days(today, -48),
            add_days(today, -48),
            "08:00",
            "15:20",
            true,
            "Excused",
            "Flu",
            "Doctor recommended one full day at home.",
        ),
        absence(
            9109,
            add_days(today, -59),
            add_days(today, -59),
            "11:45",
            "12:35",
            false,
            "Unexcused",
            "Project delivery",
            "Stayed off campus for client handover.",
        ),
        absence(
            9110,
            add_days(today, -72),
            add_days(today, -72),
            "08:00",
            "09:40",
            true,
            "Excused",
            "Cold",
            "Recovered the next day.",
        ),
        absence(
            9111,
            add_days(today, -84),
            add_days(today, -84),
            "10:45",
            "11:35",
            true,
            "Excused",
            "Family appointment",
            "Municipal office paperwork.",
        ),
        absence(
            9112,
            add_days(today, -93),
            add_days(today, -93),
            "12:35",
            "13:25",
            false,
            "Pending",
            "Late return",
            "Train strike detour.",
        ),
        absence(
            9113,
            add_days(today, -105),
            add_days(today, -105),
            "08:00",
            "08:50",
            true,
            "Excused",
            "Orthodontist",
            "Routine check.",
        ),
        absence(
            9114,
            add_days(today, -118),
            add_days(today, -118),
            "13:40",
            "14:30",
            false,
            "Unexcused",
            "Portfolio shoot",
            "Off-site photography session.",
        ),
        absence(
            9115,
            add_days(today, -129),
            add_days(today, -129),
            "08:50",
            "11:35",
            true,
            "Excused",
            "Migraine",
            "Submitted note after recovery.",
        ),
        absence(
            9116,
            add_days(today, -141),
            add_days(today, -141),
            "09:55",
            "12:35",
            true,
            "Excused",
            "Workshop",
            "Guest session with design alumni.",
        ),
        absence(
            9117,
            add_days(today, -156),
            add_days(today, -156),
            "08:00",
            "09:40",
            false,
            "Pending",
            "Traffic",
            "Motorway closure after accident.",
        ),
        absence(
            9118,
            add_days(today, -171),
            add_days(today, -171),
            "11:45",
            "13:25",
            true,
            "Excused",
            "University visit",
            "Campus tour in Graz.",
        ),
        absence(
            9119,
            add_days(today, -188),
            add_days(today, -188),
            "08:00",
            "15:20",
            true,
            "Excused",
            "Stomach bug",
            "One-day recovery.",
        ),
        absence(
            9120,
            add_days(today, -204),
            add_days(today, -204),
            "10:45",
            "12:35",
            false,
            "Unexcused",
            "Missed reminder",
            "Forgot timetable change after holiday.",
        ),
        absence(
            9121,
            add_days(today, -227),
            add_days(today, -227),
            "13:40",
            "15:20",
            true,
            "Excused",
            "Driving lesson",
            "Final mandatory road practice.",
        ),
        absence(
            9122,
            add_days(today, -253),
            add_days(today, -253),
            "08:50",
            "09:40",
            false,
            "Pending",
            "Overslept",
            "Alarm sync issue after update.",
        ),
        absence(
            9123,
            add_days(today, -281),
            add_days(today, -281),
            "09:55",
            "10:45",
            true,
            "Excused",
            "Doctor",
            "Annual checkup.",
        ),
        absence(
            9124,
            add_days(today, -316),
            add_days(today, -316),
            "08:00",
            "11:35",
            true,
            "Excused",
            "Family event",
            "Cousin's civil ceremony.",
        ),
    ];

    items.sort_by(compare_absence_newest_first);
    items
}

pub fn demo_summary_line() -> String {
    let today = format_date(today_local());
    format!("Bundled portfolio dataset refreshed around {today}")
}

#[derive(Clone, Copy)]
struct LessonMeta<'a> {
    cell_state: &'a str,
    teacher: &'a str,
    teacher_long_name: &'a str,
    room: &'a str,
    room_long_name: &'a str,
    classes: &'a [&'a str],
    lesson_text: &'a str,
    remarks: &'a str,
    cancelled: bool,
    substitution: bool,
}

fn period(name: &str, start: &str, end: &str) -> TimeUnit {
    TimeUnit {
        name: name.to_owned(),
        start_time: start.to_owned(),
        end_time: end.to_owned(),
    }
}

fn lesson(
    instance_id: &str,
    subject: &str,
    subject_long_name: &str,
    start_time: &str,
    end_time: &str,
    meta: LessonMeta<'_>,
) -> ParsedLesson {
    ParsedLesson {
        instance_id: instance_id.to_owned(),
        subject: subject.to_owned(),
        subject_long_name: subject_long_name.to_owned(),
        lesson_text: meta.lesson_text.to_owned(),
        cell_state: meta.cell_state.to_owned(),
        teacher: meta.teacher.to_owned(),
        teacher_long_name: meta.teacher_long_name.to_owned(),
        all_teachers: vec![meta.teacher.to_owned()],
        all_teacher_long_names: vec![meta.teacher_long_name.to_owned()],
        room: meta.room.to_owned(),
        room_long_name: meta.room_long_name.to_owned(),
        all_classes: meta
            .classes
            .iter()
            .map(|class| (*class).to_owned())
            .collect(),
        start_time: start_time.to_owned(),
        end_time: end_time.to_owned(),
        cancelled: meta.cancelled,
        substitution: meta.substitution,
        remarks: meta.remarks.to_owned(),
    }
}

fn absence(
    id: i64,
    start_date: NaiveDate,
    end_date: NaiveDate,
    start_time: &str,
    end_time: &str,
    is_excused: bool,
    excuse_status: &str,
    reason: &str,
    text: &str,
) -> ParsedAbsence {
    ParsedAbsence {
        id,
        student_name: "Portfolio Demo".to_owned(),
        reason: reason.to_owned(),
        text: text.to_owned(),
        excuse_status: excuse_status.to_owned(),
        is_excused,
        start_date,
        end_date,
        start_time: start_time.to_owned(),
        end_time: end_time.to_owned(),
    }
}

fn demo_timegrid() -> Vec<TimeUnit> {
    vec![
        period("0. EH", "07:05", "07:55"),
        period("1. EH", "08:00", "08:50"),
        period("2. EH", "08:55", "09:45"),
        period("3. EH", "09:55", "10:45"),
        period("4. EH", "10:55", "11:45"),
        period("5. EH", "11:50", "12:40"),
        period("6. EH", "12:45", "13:35"),
        period("7. EH", "13:40", "14:30"),
        period("8. EH", "14:35", "15:25"),
        period("9. EH", "15:30", "16:20"),
        period("10. EH", "16:25", "17:15"),
        period("11. EH", "17:20", "18:05"),
        period("12. EH", "18:05", "18:50"),
        period("13. EH", "19:00", "19:45"),
        period("14. EH", "19:45", "20:30"),
        period("15. EH", "20:40", "21:25"),
    ]
}

fn own_week_lessons() -> [Vec<ParsedLesson>; 5] {
    [
        vec![
            lesson(
                "own-mon-mat",
                "MAT",
                "Advanced Mathematics",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "SUBSTITUTION",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF"],
                    lesson_text: "Data viz sprint",
                    remarks: "Room swap after projector failure.",
                    cancelled: false,
                    substitution: true,
                },
            ),
            lesson(
                "own-mon-eng",
                "ENG",
                "English Studio",
                "08:00",
                "08:50",
                LessonMeta {
                    cell_state: "",
                    teacher: "NOVA",
                    teacher_long_name: "Noa Varga",
                    room: "B-204",
                    room_long_name: "Seminar B-204",
                    classes: &["5AHIF"],
                    lesson_text: "Pitch rehearsal",
                    remarks: "Bring the two-minute product intro.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "own-mon-uix",
                "UIX",
                "Interface Lab",
                "09:55",
                "11:35",
                LessonMeta {
                    cell_state: "",
                    teacher: "KERN",
                    teacher_long_name: "Mara Kern",
                    room: "LAB-5",
                    room_long_name: "Prototype Lab 5",
                    classes: &["5AHIF"],
                    lesson_text: "Ratios + spacing pass",
                    remarks: "Crit at 10:45 with guest reviewers.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "own-mon-his",
                "HIS",
                "Contemporary History",
                "13:40",
                "14:30",
                LessonMeta {
                    cell_state: "EXAM",
                    teacher: "ORTL",
                    teacher_long_name: "Lena Ortlieb",
                    room: "A-113",
                    room_long_name: "History Room A-113",
                    classes: &["5AHIF"],
                    lesson_text: "Sources essay",
                    remarks: "Open notes on primary sources only.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![
            lesson(
                "own-tue-phy",
                "PHY",
                "Applied Physics",
                "08:50",
                "10:45",
                LessonMeta {
                    cell_state: "",
                    teacher: "RIED",
                    teacher_long_name: "Johann Riedl",
                    room: "LAB-2",
                    room_long_name: "Physics Lab 2",
                    classes: &["5AHIF"],
                    lesson_text: "Sensors + noise",
                    remarks: "Bring the oscilloscope worksheet.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "own-tue-che",
                "CHE",
                "Chemistry",
                "10:45",
                "11:35",
                LessonMeta {
                    cell_state: "CANCELLED",
                    teacher: "HAAS",
                    teacher_long_name: "Sofia Haas",
                    room: "LAB-1",
                    room_long_name: "Chemistry Lab 1",
                    classes: &["5AHIF"],
                    lesson_text: "",
                    remarks: "",
                    cancelled: true,
                    substitution: false,
                },
            ),
            lesson(
                "own-tue-pro",
                "PRO",
                "Project Block",
                "11:45",
                "13:25",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "STU-3",
                    room_long_name: "Studio 3",
                    classes: &["5AHIF"],
                    lesson_text: "Portfolio polish",
                    remarks: "Ship candidate build by lunch.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![
            lesson(
                "own-wed-net",
                "NET",
                "Network Systems",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "",
                    teacher: "KALT",
                    teacher_long_name: "Nils Kalt",
                    room: "C-205",
                    room_long_name: "Networking Lab C-205",
                    classes: &["5AHIF"],
                    lesson_text: "VPN failover",
                    remarks: "Packet captures graded today.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "own-wed-eth",
                "ETH",
                "Ethics",
                "11:45",
                "12:35",
                LessonMeta {
                    cell_state: "",
                    teacher: "FREI",
                    teacher_long_name: "Lea Frei",
                    room: "A-009",
                    room_long_name: "Forum Room A-009",
                    classes: &["5AHIF"],
                    lesson_text: "AI authorship",
                    remarks: "Come with one example for debate.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![
            lesson(
                "own-thu-web",
                "WEB",
                "Web Engineering",
                "09:55",
                "11:35",
                LessonMeta {
                    cell_state: "",
                    teacher: "NOVA",
                    teacher_long_name: "Noa Varga",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF"],
                    lesson_text: "Design tokens",
                    remarks: "Review the deploy preview before class.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "own-thu-spt",
                "SPT",
                "Sports",
                "13:40",
                "15:20",
                LessonMeta {
                    cell_state: "",
                    teacher: "WOLF",
                    teacher_long_name: "Eva Wolf",
                    room: "GYM",
                    room_long_name: "Main Gym",
                    classes: &["5AHIF"],
                    lesson_text: "Climbing circuit",
                    remarks: "Indoor shoes required.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![
            lesson(
                "own-fri-dbs",
                "DBS",
                "Database Systems",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "",
                    teacher: "TANG",
                    teacher_long_name: "Li Tang",
                    room: "LAB-3",
                    room_long_name: "Data Lab 3",
                    classes: &["5AHIF"],
                    lesson_text: "Index strategy",
                    remarks: "Bring yesterday's query plan notes.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "own-fri-pro",
                "PRO",
                "Project Review",
                "11:45",
                "13:25",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "AUD-2",
                    room_long_name: "Auditorium 2",
                    classes: &["5AHIF"],
                    lesson_text: "Sprint retro",
                    remarks: "Demo day line-up is finalised here.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
    ]
}

fn class_week_lessons() -> [Vec<ParsedLesson>; 5] {
    [
        vec![
            lesson(
                "class-mon-pro",
                "PRO",
                "Project Block",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "STU-3",
                    room_long_name: "Studio 3",
                    classes: &["5AHIF"],
                    lesson_text: "Client dry run",
                    remarks: "Morning is split across presentation teams.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "class-mon-mat",
                "MAT",
                "Advanced Mathematics",
                "09:55",
                "11:35",
                LessonMeta {
                    cell_state: "",
                    teacher: "KERN",
                    teacher_long_name: "Mara Kern",
                    room: "B-112",
                    room_long_name: "Seminar B-112",
                    classes: &["5AHIF"],
                    lesson_text: "Systems modelling",
                    remarks: "Worksheet check in the first 10 minutes.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![
            lesson(
                "class-tue-net",
                "NET",
                "Network Systems",
                "08:50",
                "10:45",
                LessonMeta {
                    cell_state: "",
                    teacher: "KALT",
                    teacher_long_name: "Nils Kalt",
                    room: "C-205",
                    room_long_name: "Networking Lab C-205",
                    classes: &["5AHIF"],
                    lesson_text: "Campus routing",
                    remarks: "Teams rotate through switch racks.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "class-tue-eng",
                "ENG",
                "English Studio",
                "11:45",
                "12:35",
                LessonMeta {
                    cell_state: "",
                    teacher: "NOVA",
                    teacher_long_name: "Noa Varga",
                    room: "B-204",
                    room_long_name: "Seminar B-204",
                    classes: &["5AHIF"],
                    lesson_text: "Interview practice",
                    remarks: "Each team presents one product story.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![
            lesson(
                "class-wed-web",
                "WEB",
                "Web Engineering",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "",
                    teacher: "NOVA",
                    teacher_long_name: "Noa Varga",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF"],
                    lesson_text: "Design system pass",
                    remarks: "Workshop format, laptops open all lesson.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "class-wed-spt",
                "SPT",
                "Sports",
                "13:40",
                "15:20",
                LessonMeta {
                    cell_state: "",
                    teacher: "WOLF",
                    teacher_long_name: "Eva Wolf",
                    room: "GYM",
                    room_long_name: "Main Gym",
                    classes: &["5AHIF"],
                    lesson_text: "Climbing circuit",
                    remarks: "Bring the outdoor jacket.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![lesson(
            "class-thu-dbs",
            "DBS",
            "Database Systems",
            "09:55",
            "11:35",
            LessonMeta {
                cell_state: "",
                teacher: "TANG",
                teacher_long_name: "Li Tang",
                room: "LAB-3",
                room_long_name: "Data Lab 3",
                classes: &["5AHIF"],
                lesson_text: "EXPLAIN plans",
                remarks: "Optimisation challenge with prizes.",
                cancelled: false,
                substitution: false,
            },
        )],
        vec![lesson(
            "class-fri-his",
            "HIS",
            "Contemporary History",
            "08:00",
            "08:50",
            LessonMeta {
                cell_state: "EXAM",
                teacher: "ORTL",
                teacher_long_name: "Lena Ortlieb",
                room: "A-113",
                room_long_name: "History Room A-113",
                classes: &["5AHIF"],
                lesson_text: "Essay checkpoint",
                remarks: "Short written reflection at the end.",
                cancelled: false,
                substitution: false,
            },
        )],
    ]
}

fn room_week_lessons() -> [Vec<ParsedLesson>; 5] {
    [
        vec![
            lesson(
                "room-mon-web",
                "WEB",
                "Web Engineering",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "",
                    teacher: "NOVA",
                    teacher_long_name: "Noa Varga",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF", "5BHITM"],
                    lesson_text: "Shared lab review",
                    remarks: "Double-booked intentionally for demo overlap.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "room-mon-mat",
                "MAT",
                "Advanced Mathematics",
                "08:00",
                "08:50",
                LessonMeta {
                    cell_state: "SUBSTITUTION",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF"],
                    lesson_text: "Moved from B-112",
                    remarks: "Short room swap because of maintenance.",
                    cancelled: false,
                    substitution: true,
                },
            ),
            lesson(
                "room-mon-pro",
                "PRO",
                "Project Block",
                "11:45",
                "13:25",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF"],
                    lesson_text: "Crit wall build",
                    remarks: "Pin-up occupies the full north wall.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![],
        vec![lesson(
            "room-wed-uix",
            "UIX",
            "Interface Lab",
            "09:55",
            "11:35",
            LessonMeta {
                cell_state: "",
                teacher: "KERN",
                teacher_long_name: "Mara Kern",
                room: "LAB-7",
                room_long_name: "Interaction Lab 7",
                classes: &["4AHIF"],
                lesson_text: "Component critique",
                remarks: "Big screen reserved for live walkthroughs.",
                cancelled: false,
                substitution: false,
            },
        )],
        vec![lesson(
            "room-thu-aud",
            "AUD",
            "Open Studio",
            "13:40",
            "15:20",
            LessonMeta {
                cell_state: "",
                teacher: "MILL",
                teacher_long_name: "Mila Iller",
                room: "LAB-7",
                room_long_name: "Interaction Lab 7",
                classes: &["5AHIF", "4AHIF"],
                lesson_text: "Portfolio camera tests",
                remarks: "Lighting rigs stay up until Friday.",
                cancelled: false,
                substitution: false,
            },
        )],
        vec![],
    ]
}

fn teacher_week_lessons() -> [Vec<ParsedLesson>; 5] {
    [
        vec![
            lesson(
                "teacher-mon-mat",
                "MAT",
                "Advanced Mathematics",
                "08:00",
                "09:40",
                LessonMeta {
                    cell_state: "SUBSTITUTION",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["5AHIF"],
                    lesson_text: "Portfolio metrics",
                    remarks: "Demo branch showcases target switching.",
                    cancelled: false,
                    substitution: true,
                },
            ),
            lesson(
                "teacher-mon-pro",
                "PRO",
                "Project Block",
                "11:45",
                "13:25",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "STU-3",
                    room_long_name: "Studio 3",
                    classes: &["5AHIF"],
                    lesson_text: "Client rehearsal",
                    remarks: "Milestone review with two mentors.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![lesson(
            "teacher-tue-pro",
            "PRO",
            "Project Block",
            "09:55",
            "11:35",
            LessonMeta {
                cell_state: "",
                teacher: "MILL",
                teacher_long_name: "Mila Iller",
                room: "STU-3",
                room_long_name: "Studio 3",
                classes: &["5BHITM"],
                lesson_text: "Motion pass",
                remarks: "Review transitions and staging.",
                cancelled: false,
                substitution: false,
            },
        )],
        vec![
            lesson(
                "teacher-wed-adv",
                "ADV",
                "Advisory",
                "08:50",
                "09:40",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "A-021",
                    room_long_name: "Mentoring Room A-021",
                    classes: &["5AHIF"],
                    lesson_text: "Capstone check-in",
                    remarks: "Each team gets a 10 minute slot.",
                    cancelled: false,
                    substitution: false,
                },
            ),
            lesson(
                "teacher-wed-uix",
                "UIX",
                "Interface Lab",
                "13:40",
                "15:20",
                LessonMeta {
                    cell_state: "",
                    teacher: "MILL",
                    teacher_long_name: "Mila Iller",
                    room: "LAB-7",
                    room_long_name: "Interaction Lab 7",
                    classes: &["4AHIF"],
                    lesson_text: "Crit wall",
                    remarks: "End with one concrete revision per team.",
                    cancelled: false,
                    substitution: false,
                },
            ),
        ],
        vec![lesson(
            "teacher-thu-pro",
            "PRO",
            "Project Block",
            "11:45",
            "13:25",
            LessonMeta {
                cell_state: "",
                teacher: "MILL",
                teacher_long_name: "Mila Iller",
                room: "AUD-2",
                room_long_name: "Auditorium 2",
                classes: &["5AHIF"],
                lesson_text: "Pitch queue",
                remarks: "Room staging starts at 11:30.",
                cancelled: false,
                substitution: false,
            },
        )],
        vec![lesson(
            "teacher-fri-open",
            "OPEN",
            "Open Studio",
            "08:00",
            "10:45",
            LessonMeta {
                cell_state: "",
                teacher: "MILL",
                teacher_long_name: "Mila Iller",
                room: "LAB-7",
                room_long_name: "Interaction Lab 7",
                classes: &["5AHIF", "5BHITM"],
                lesson_text: "Weekly showcase",
                remarks: "Portfolio visitors can join this session.",
                cancelled: false,
                substitution: false,
            },
        )],
    ]
}
